# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6043f218226adf4a74db45dbfcfab6d5e1ffd01119a89b1796d9ccb1c5f0d93396c235bbe9617713f7de690430bea94c44f8dfcd98ab4eed2ed42d6dbd84b91

test:
  secret_key_base: 4867f4876a8c5e0a64fb647862ebf17ff61a922c75c795217091454d018c809d768e8207e906d11f4d2bf8a7fb09a1b26923f0a4d327016ab614af4ccc9a1ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
